version: '3.7'
services:
  dynamodb-local:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    ports:
      - "8000:8000"
  puzzle-solver:
    build: .
    depends_on:
      - dynamodb-local
    container_name: puzzle-solver-app
    ports:
      - "3000:3000"
      - "9229:9229"
    expose:
      - 9229
    volumes:
      - .:/puzzle-solver-app 
    environment:
      NODE_ENV: 'development'
      AWS_ACCESS_KEY_ID: 'DUMMYIDEXAMPLE'
      AWS_SECRET_ACCESS_KEY: 'DUMMYEXAMPLEKEY'
    command: npm run debug